name: example
description: A simple command-line application.
version: 1.0.0
# homepage: https://www.example.com
environment:
  sdk: ">=2.14.3 <3.0.0"

dev_dependencies:
  import_lint:
    git:
      url: https://github.com/lfariaUnifei/import-lint
      ref: test
  lints: ^2.0.0
  dart_code_metrics: ^4.16.0
