name: import_lint_loader
description: bootstrap package of import_lint
version: 0.9.3
publish_to: none

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  import_lint:
    git:
      url: https://github.com/lfariaUnifei/import-lint
      ref: test
#  import_lint: ^0.9.3
